version: "3.8"
services:
  eureka:
    container_name: eureka-server
    build: .
    restart: always
    ports:
      - "8761:8761"
    networks:
      - pc-local
networks:
  pc-local:
    external: true
